# Generated by Django 4.0.5 on 2022-06-05 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate_id', models.CharField(blank=True, max_length=225, null=True)),
                ('postage_label', models.CharField(blank=True, max_length=225, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=225, null=True)),
                ('carrer', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=256)),
                ('from_street1', models.CharField(max_length=50)),
                ('from_street2', models.CharField(default=None, max_length=50)),
                ('from_zip', models.IntegerField(max_length=10)),
                ('from_phone', models.IntegerField(max_length=10)),
                ('from_state', models.CharField(max_length=3)),
                ('from_country', models.CharField(default='US', max_length=3)),
                ('to_street1', models.CharField(max_length=50)),
                ('to_street2', models.CharField(default=None, max_length=50)),
                ('to_zip', models.IntegerField(max_length=10)),
                ('to_phone', models.IntegerField(max_length=10)),
                ('to_state', models.CharField(max_length=3)),
                ('to_country', models.CharField(default='US', max_length=3)),
                ('length', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('width', models.FloatField(default=1)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('shipment_id', models.ManyToManyField(to='api.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order_status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=256)),
                ('street2', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('country', models.CharField(default='US', max_length=5)),
                ('is_default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
