# Generated by Django 4.0.5 on 2022-06-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_detail_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
