# Generated by Django 4.0.5 on 2022-06-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer_is_admin_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_admin',
        ),
    ]
