# Generated by Django 4.0.5 on 2022-06-10 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_remove_customer_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=10)),
                ('length', models.FloatField(default=10)),
                ('width', models.FloatField(default=10)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=256)),
                ('shipment_id', models.CharField(max_length=256)),
                ('rate_id', models.CharField(blank=True, max_length=225, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price_user', models.FloatField(blank=True, null=True)),
                ('price_admin', models.FloatField(blank=True, null=True)),
                ('postage_label', models.CharField(blank=True, max_length=225, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=225, null=True)),
                ('carrier', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, max_length=20, null=True)),
                ('parcel', models.ManyToManyField(blank=True, null=True, to='api.parcel')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
