# Generated by Django 4.0.5 on 2022-06-12 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_order_order_id_alter_order_shipment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=20)),
                ('from_phone', models.CharField(max_length=10)),
                ('from_street1', models.CharField(max_length=20)),
                ('from_state', models.CharField(max_length=3)),
                ('from_city', models.CharField(max_length=20)),
                ('from_country', models.CharField(max_length=10)),
                ('to_name', models.CharField(max_length=20)),
                ('to_phone', models.CharField(max_length=10)),
                ('to_street1', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=3)),
                ('to_city', models.CharField(max_length=20)),
                ('to_country', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shipment'),
            preserve_default=False,
        ),
    ]
