# Generated by Django 4.0.5 on 2022-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_shipment_parcel_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='shipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='parcel',
            field=models.ManyToManyField(related_name='shipments', to='api.parcel'),
        ),
    ]
