# Generated by Django 4.0.5 on 2022-06-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_parcel_shipment_shipment_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=256)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckPriceShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_carrier', models.CharField(max_length=20)),
                ('choice_service', models.CharField(max_length=256)),
                ('servicecarrier', models.ManyToManyField(to='api.servicecarrier')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shipment')),
            ],
        ),
    ]
