# Generated by Django 4.0.5 on 2022-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_servicecarrier_checkpriceshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='from_zip',
            field=models.CharField(default=123123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_zip',
            field=models.CharField(default=123123, max_length=10),
            preserve_default=False,
        ),
    ]
