# Generated by Django 4.0.5 on 2022-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shipment_from_zip_shipment_to_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='from_street1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_street1',
            field=models.CharField(max_length=50),
        ),
    ]
