# Generated by Django 4.0.5 on 2022-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_shipment_from_street1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpriceshipment',
            name='servicecarrier',
            field=models.ManyToManyField(blank=True, null=True, to='api.servicecarrier'),
        ),
    ]
