# Generated by Django 4.0.5 on 2022-06-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_checkpriceshipment_servicecarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipment_id',
        ),
    ]
