# Generated by Django 4.0.5 on 2022-06-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_order_shipment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rate_id',
        ),
    ]
