# Generated by Django 4.0.5 on 2022-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parcel',
            field=models.ManyToManyField(related_name='orders', to='api.parcel'),
        ),
    ]
