# Generated by Django 4.0.5 on 2022-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_order_parcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postage_label',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='parcel',
            name='postage_label',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkpriceshipment',
            name='choice_service',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkpriceshipment',
            name='servicecarrier',
            field=models.ManyToManyField(to='api.servicecarrier'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecarrier',
            name='service',
            field=models.CharField(max_length=255),
        ),
    ]
